const DUMMY_LIST = [
  {
    id: "p1",
    title: "Cordless Drill",
    brand: "BOSCH 18v",
    description:
      "The Bosch GSB 180-Li 18V Cordless Impact Drill has a max screw diameter of 10 mm. The tool is Highly Serviceable, as the Motor has changeable carbon brushes for easy maintenance and serviceability. The Cordless Drill is also extremely durable, as it's designed with Robust Housing and Battery Cell Protection. The 2-gear feature offers Optimized Torque for screwdriving and speed for drilling, thanks to 2-Speed Planetary Gearbox",
    image: "/img/products/drill2.png",
    price: 9000,
    warranty: 12,
    origin: "INDIA",
    fav: true,
  },
  {
    id: "p2",
    title: "Angle Grinder",
    brand: 'DEWALT 4.5"',
    description:
      "Small Angle Grinder Tool with No Lock-on has a powerful 9 Amp motor with overload protection for fast material removal, a slim design of 4.5 grinder to add comfort for extended use, and a low-profile construction for operating in tight spaces.",
    image: "/img/products/grinder1.png",
    price: 8000,
    warranty: 24,
    origin: "INDIA",
    fav: false,
  },
  {
    id: "p3",
    title: "TMT Rebar",
    brand: "TATA",
    description: "Steel reinforcement bars (Rebars) which go through an intensive thermo mechanical treatment (TMT) are known as TMT Rebars. Their high strength and flexibility make them useful in reinforced cement concrete (RCC) work and large scale construction projects. ",
    image: "/img/products/tmt.png",
    price: 1500,
    warranty: 6,
    origin: "INDIA",
    fav: false,
  },
  {
    id: "p4",
    title: "Gas Chainsaw",
    brand: "Husqvarna",
    description: "Husqvarna 400 Series chainsaws are excellent all-around saws for outdoor projects, from tree-pruning to felling trees. Compact and versatile with innovative safety features, these gas-powered chainsaws are designed to maximize your cutting power and minimize fuel consumption.",
    image: "/img/products/chainsaw1.png",
    price: 4000,
    warranty: 6,
    origin: "INDIA",
    fav: false,
  },
  {
    id: "p5",
    title: "Cement Bag ",
    brand: "Ultratech",
    description: "Portland Pozzolana Cement Portland Pozzolana cement is ordinary Portland cement intimately blended or interground with pozzolanic materials such as fly ash, calcined clay, rice husk ash etc . Portland cement clinker is either interground or intimately blended ",
    image: "/img/products/cement.png",
    price: 400,
    warranty: 1,
    origin: "INDIA",
    fav: false,
  },
  {
    id: "p6",
    title: "paint 10L White Base",
    brand: "Indigo",
    description: "Indigo 10L White Base Gold Series Exterior Emulsions is a premium quality product from Indigo . Moglix is a well-known ecommerce platform for qualitative range of Exterior Paints. All Indigo 10L White Base Gold Series Exterior Emulsions are manufactured by using quality assured material and advanced techniques, which make them up to the standard in this highly challenging field.",
    image: "/img/products/paint.png",
    price: 300,
    warranty: 24,
    origin: "INDIA",
    fav: false,
  },
];

export default DUMMY_LIST;
